title: "Programar do Zero"
url: "https://programardozero.com.br"
baseurl: ""

collections:
  trails:
    output: true
  courses:
    output: true
    permalink: /courses/:path/

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

defaults:
  - scope:
      path: "courses/*/*.md"
      type: "pages"
    values:
      permalink: "/courses/:path/:id/"

exclude:
  - Procfile.dev
  - node_modules
  - package.json
  - package-lock.json
  - assets/css/main.tailwind.css
  - assets/js/controllers
  - assets/js/main.js
