title: "Programar do Zero"
url: "https://programardozero.com.br"
baseurl: ""

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Procfile.dev
  - node_modules
  - package.json
  - package-lock.json
  - assets/css/main.tailwind.css
  - assets/js/controllers
  - assets/js/main.js
